### PR TITLE
Update concat-map.md

### PR DESCRIPTION
**Pull request by phalgunv**
Corrected to mention inner observable, instead of source observable.

### CODE REVIEW

**Comment by phalgunv** [comment]
@maxkoretskyi 

I've made minor fixes to the description. Please let me know if you have any comments.

**Comment by phalgunv** [comment]
@VarvaraSandakova Would you let me know if there was any issue with commit?

**Comment by maxkoretskyi** [comment]
[this one](https://github.com/indepth-dev/community/pull/188/commits) seems to be suggesting similar changes, right?

**Comment by phalgunv** [comment]
@maxkoretskyi Yes.

**Pull request closed without merging**
