### PR TITLE
feat(zip operator): update zip.md

### PR DESCRIPTION
**Pull request by huantaoliu**

### CODE REVIEW

**Comment by profileEnumerable** [comment]
Pls consider this change

**Comment by maxkoretskyi** [comment]
@profileEnumerable but as I commented inline, the change is incorrect.

**Comment by huantaoliu** [comment]
@maxkoretskyi if you can check here, zip completes before inner observable b. thanks.
https://stackblitz.com/edit/indepth-rxjs-zip-oc497j?file=index.ts,utils.ts

**Comment by maxkoretskyi** [comment]
@huantaoliu , yeah, you're right. Thanks! We need to edit this. What about `and no more cached pairs to emit`?

**Comment by huantaoliu** [comment]
@maxkoretskyi I updated the example, to mimic the following senario:  zip(A, B)
 - A emit 3 items before B even start, get cached and complete.
 - B keep emiting every 5 sec
 -zip will emit whenever it get a pair, so after zip emit 3 items, no more cached, Zip will complete.

**Comment by maxkoretskyi** [comment]
@huantaoliu, yeah, I see now what you mean. Have never tested the case when one observable completes before the second one starts emitting. I find it a bit unintuitive that `zip` doesn't complete without emitting anything or emits just one pair with last value from the completed stream and a pair value from the non-completed stream. Great finding and research! Thanks for the contribution 👍. Merged your PR.

**Pull request merged**
